### ISSUE TITLE
Tunnelling docker containers

### ISSUE THREAD

**Issue by t56k** [jamesmcm/vopono#105]
Can vopono tunnel traffic from a docker container while allowing local/LAN access?

**Comment by jamesmcm** [comment]
It's not simple because Docker also creates its own namespaces, and usually the daemon will be running outside of vopono.

One thing to try would be to just run the daemon and docker run, etc. inside the vopono namespace (e.g. run them from bash in there), note this means you can't use systemd to run the daemon though for example. Also use `--no-killswitch` to reduce the chance of networking issues.

The best thing would be probably to run OpenVPN / Wireguard in a docker container directly, and then route the other docker traffic through that. I think Whonix does something like this IIRC.

**Comment by t56k** [comment]
Ah thanks. That's kinda what I was afraid of, and since I'm technically using rootless Podman that's another issue.
