### ISSUE TITLE
Error: Could not find valid config directory

### ISSUE THREAD

**Issue by hn24** [jamesmcm/vopono#114]
Hi,
I'm tried to install vopono on a new VPS that running Ubuntu 20.04
My command is:
1. wget https://github.com/jamesmcm/vopono/releases/download/0.8.8/vopono_0.8.8_amd64.deb
2. apt install -y ./vopono_0.8.8_amd64.deb
3. vopono sync
Then, i select NordVPN and got this issue

```
root@ubuntu-1vcpu-1gb-1-0bi68:~# vopono sync
Which VPN providers do you wish to synchronise? Press Space to select and Enter to continue: NordVPN
 2021-12-03T09:01:42.231Z INFO  vopono::sync > Starting OpenVPN configuration...
Error: Could not find valid config directory!
root@ubuntu-1vcpu-1gb-1-0bi68:~#
```
Does anyone see it before?

**Comment by jamesmcm** [comment]
Why are you running it as root directly?

Try setting the `HOME` environment variable if it's not set already. e.g.
`export HOME=/root`

or when running the command: 
`HOME=/root vopono sync`



I think the issue is that when nothing is set (not `HOME` nor XDG dirs, etc.) and you're running as root, there is no check for `/root` if running as root in the final case - https://github.com/jamesmcm/vopono/blob/e10a420debc91380179f94064646448fbcbdb034/src/util/mod.rs#L61

It'd be easy to "fix" for the specific case of running as root, but I'd recommend not running it directly as root anyway.

**Comment by jamesmcm** [comment]
Also if you do want to run as root, try creating the `/root/.config` directory.

**Comment by hn24** [comment]
yeah, `/root/.config` is perfect for my case sine i just have only root account in VPS and dont want to ccreate a new once.
Thank you very much James!
