### ISSUE TITLE
exec bash not working

### ISSUE THREAD

**Issue by ak-1** [jamesmcm/vopono#174]
Things like `vopono exec bash` do not work for me anymore since 761454857f51d8be6e4a08d9da48421df50954a4.
The command is executed but it exits again right away.
All REPL commands seem to be affected. GUI programs like firefox work though.
Looks like stdin is somehow not passed properly to the process.

**Comment by jamesmcm** [comment]
I think it's because it takes over stdin - https://github.com/jamesmcm/vopono/commit/761454857f51d8be6e4a08d9da48421df50954a4#diff-9c16fd9e2af528717067a09bcd97ff4982a30a74507ca4ef09704215b6c5f719R128 

Could you test it removing line 129 from `netns.rs` ?

https://github.com/jamesmcm/vopono/blob/9d4ebc1e7c7ff6bebf37c34a69d923a0f7a7c2a5/vopono_core/src/network/netns.rs#L129

I'm on a work trip so I won't be able to re-release until Saturday at least.

We'll need to think of a better way of forwarding stdin for OpenConnect.

**Comment by ak-1** [comment]
Yes, after removing line 129 `vopono exec bash` is working again.

**Comment by jamesmcm** [comment]
Fixed in 0.10.1 release - #178
