### ISSUE TITLE
Nooby question: Alongside system-wide vpn

### ISSUE THREAD

**Issue by RAVENz46** [jamesmcm/vopono#271]
Hi, Thanks for your work! I'm sorrry for the rudimentary question.
I'd like to know
1. When system-wide VPN enable, is connection like PC -> system-wide VPN -> vopono's VPN -> server ?
2. Can I create bridged namespace to bypass system-wide VPN with vopono?

**Comment by jamesmcm** [comment]
I think it'd be the other way around, that you'd need a bridge in order to get the system-wide VPN to apply, because here the nftables rules are applying directly on the network interface.

But have you tested it? I'll try it tonight just for the simple case of running OpenVPN directly outside of vopono.
