### ISSUE TITLE
Custom OpenVPN Provider: --custom option must be path, not filename

### ISSUE THREAD

**Issue by meldafert** [jamesmcm/vopono#31]
I was trying out vopono, and basically tried to run this command:
```
$ vopono -v exec --custom custom_openvpn.ovpn --protocol openvpn "firefox"
```
However, this mysteriously faild with `Error: Failed to launch OpenVPN - is openvpn installed? Caused by: No such file or directory (os error 2)` - which was not very useful, since openvpn was installed, and all the referenced paths in the `ip netns exec ... openvpn` command existed.

After some digging, I found that `working_dir` in https://github.com/jamesmcm/vopono/blob/c84734cc1bbaacd5870e27dccc5a49e8efa822f2/src/openvpn.rs#L62 was an empty string, which caused the `No such file or directory` in `std::process::Command`. When using a relative path instead of just the filename (like the examples), it suddenly works.

This is somewhat uninituitive - I would have expected to be able to use a filename instead of a relative path, as most other CLI applications do. It would be helpful to either mention that the option must be a (relative or absolute) path, or to fallback to the current directory as `working_dir` if it is an empty string.

**Comment by jamesmcm** [comment]
Thanks! So the issue is that it can't get the parent directory if just passed the filename, and we want to use the parent directory as the working directory for running OpenVPN.

See: https://github.com/rust-lang/rust/issues/36861 - seems like a painful issue when using PathBuf as a representation of the filesystem.

I'll implement one of the workarounds proposed there, or you could try it yourself if you like as I'll be busy until Wednesday.
