### ISSUE TITLE
I am asked for my mullvad private key but I don't have any?

### ISSUE THREAD

**Issue by Sojiro84** [jamesmcm/vopono#55]
So, I use by default, the Mullvad app but I want to only have specific apps use it.

I found this project and seems like it would be perfect for me. I installed it, started the sync, gave my account number and picked the public key.

Then I am asked for my private key but what is it and where do I find it? There aren't any on my Mullvad account page and googling around also did not provide answers. And this projects setting up page also did not mentioned private key's.

Anyone here know where I can find the private key?

**Comment by jamesmcm** [comment]
If you don't have the private key for the keypair I think you will need to generate a new keypair.

You can select the option in the menu to do it automatically, and Mullvad allows several separate keypairs so it shouldn't be a problem.

**Comment by joelpet** [comment]
To add to @jamesmcm's perfectly correct answer:

For each public key listed on your Mullvad account page, there is a counterpart – a private key – that the public key was derived from. Whoever knows a private key can identify as the owner of the public key. In this context, it means that whoever has the private key can use your Mullvad account as if they were you.

Typically, a private key should be generated on the machine on which it's intended to be used. It should be protected so that it is only ever accessible only by the key owner's user account on that machine.

**Comment by Sojiro84** [comment]
Thanks for the answer. I did generate a new public key in the mullvad app and that also appears on the mullvad website but nowhere is the private key mentioned. Strange.

**Comment by joelpet** [comment]
It's most likely stored somewhere on the device that you are running the Mullvad app on. It's not normally something a user need be concerned with, so it doesn't surprise me that the Mullvad app does not mention it. 

If you're not able to find the private key that the Mullvad app generated, you can let `vopono` generate a new key pair for you, as was suggested in https://github.com/jamesmcm/vopono/issues/55#issuecomment-748605890.

**Comment by Sojiro84** [comment]
Ahh, now I get what he said. I probably missed that option when I used vopono. Going to try it when I get home!

**Comment by Sojiro84** [comment]
That was it, I got it working now by letting vopono generate a key. Thanks for the help!
