### ISSUE TITLE
Config file not read?

### ISSUE THREAD

**Issue by dani-jozsef** [jamesmcm/vopono#75]
Apparently the config file isn't read by vopono.

```
dani@gorillo:~/.config/vopono$ ls
config.toml  locks  mv

dani@gorillo:~/.config/vopono$ cat config.toml 
dns = "127.0.0.16"
firewall = "IpTables"
protocol = "Wireguard"
provider = "Mullvad"
postup = "/home/dani/bin/vpn_postup"
predown = "/home/dani/bin/vpn_predn"

dani@gorillo:~/.config/vopono$ vopono exec --server=sweden bash
 2021-04-09T15:03:16.400Z INFO  vopono::util > Calling sudo for elevated privileges, current user will be used as default user
[sudo] password for dani: 
thread 'main' panicked at 'Enter a VPN provider', src/exec.rs:53:41
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

dani@gorillo:~/.config/vopono$ vopono exec bash
 2021-04-09T15:03:24.274Z INFO  vopono::util > Calling sudo for elevated privileges, current user will be used as default user
[sudo] password for dani: 
thread 'main' panicked at 'Enter a VPN provider', src/exec.rs:53:41
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I'm not sure what's wrong... :)

**Comment by jamesmcm** [comment]
Hey,

Can you please check it's running the latest version:

> $ vopono --version
> vopono 0.7.0

Also make sure you don't have your XDG config dir or home dir environment variables set to anything unusual. Running it in verbose mode might give a better idea, but I'm not sure if I added a debug message for the attempted config file reading (I will add one).

Also I think I forgot to add the DNS as a key so I'll take a look at that later.

**Comment by dani-jozsef** [comment]
Okay so first it really was a stuck version. ${HOME}/.cargo/bin isn't in the path when vopono restarts itself with sudo, and so I forgot there was a copy of it in /usr/local/bin.

**Comment by jamesmcm** [comment]
I always the cargo bin dir to my path, I haven't tested it with the suid set.

You can try to test it (just set the suid bit on the binary), the main question will be about how the sudo crate works. In theory, it should realise it doesn't need to escalate with sudo at that point.

**Comment by rff** [comment]
Not sure if I should add a new issue. But I have the same problem.

It does not work for me because my user home dir is different than the username. In fact, looking at `mod/utils/mod.rs:config_dir()` it seems that any user directory that don't follow the standard `/home/<user>/.config/` will not work (after sudoing). I google a little and didn't find any easy way to probe that without spawning a shellscript or parsing `/etc/passwd`. But I think one solution is to cache `$HOME` before changing to sudo? That way you don't need to guess and can even use `$XDG_CONFIG_HOME` or one of the fancier crates like [dirs](https://crates.io/crates/dirs) or [directories](https://crates.io/crates/directories).

**Comment by jamesmcm** [comment]
This actually used to use `directories`, there are cases where that doesn't work as intended with sudo too (if the xdg dirs are set for root for example), so I think your proposal is the best option. The code might also have changed enough since then that `directories` would work correctly too maybe.

We can check that it correctly forwards `$HOME` too.

**Comment by rff** [comment]
@jamesmcm Sorry for the delay. I had forgot about it.
I can confirm that it works, in fact it is the same workaround I did on the same day but I procrastinated to send a PR.
Really thanks for the fix and again, I am sorry to take so long for me to reply.

**Comment by jamesmcm** [comment]
No problem, thanks for reporting it.
